### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by zhaotuo0815** [ImLaoBJie/ActuatedSignalControl#5]
你好，我在运行您的main函数的时候，发现您导入了（import wx
from pubsub import pub）的文件里边并没有wx和pubsub这两个函数呀，望您指教，万分谢谢！

**Comment by ImLaoBJie** [comment]
pip install wx
pip install pubsub
这两是public dependency

**Comment by zhaotuo0815** [comment]
哦哦、好的好的、非常感谢！祝好



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HE Hj ***@***.***&gt;
发送时间: 2021年12月2日 11:34
收件人: ImLaoBJie/ActuatedSignalControl ***@***.***&gt;
抄送: zhao tuo ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ImLaoBJie/ActuatedSignalControl] 问题请教 (Issue #5)
